server:
    port: 9091
spring:
  datasource:
    url: jdbc:sqlserver://ejai.database.windows.net:1433;databaseName=JonesGo;
    username: CloudSAcdf5231d
    password: ${password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:

    show-sql: true